### ISSUE TITLE
User Story 10: As a player, I want to click on a picture of a character and turn it around to narrow down the pool of possible people. Furthermore, I want this action to be reversible in case I am unsure about my decision.

### ISSUE THREAD

**Issue by LiamK21** [sopra-fs24-group-34/sopra-fs24-group-34-client#9]
- [x] sopra-fs24-group-34/sopra-fs24-group-34-client#5
- [x] sopra-fs24-group-34/sopra-fs24-group-34-client#4
- [x] sopra-fs24-group-34/sopra-fs24-group-34-client#3
- [x] sopra-fs24-group-34/sopra-fs24-group-34-client#2

**Comment by LiamK21** [comment]
See pull request #56
